export const basic = {
	ADD_VALUE: 'ADD_VALUE',
	CLEAR_DATA: 'CLEAR_DATA',
	ADD_SYMBOL: 'ADD_SYMBOL',
	MAKE_SIGNED_VALUE: 'MAKE_SIGNED_VALUE',
	DISPLAY_HISTORY: 'DISPLAY_HISTORY',
	ADD_HISTORY: 'ADD_HISTORY',
	CLEAR_DISPLAY_VALUE: 'CLEAR_DISPLAY_VALUE',
	STEP_BACKWARD: 'STEP_BACKWARD'
};